Add messenger react app
wikimedia/edx-platform pull request #1
Opened 2021-09-02 12:10 UTC by tehreem-sadat

## Description

Add Messenger app: https://www.loom.com/share/39d0c3cba2a14bfbad8d7fc586a0bf3a

2021-09-02 12:50 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/api/v0/serializers.py
> +        raise serializers.ValidationError('User does not exist - invalid username {}'.format(username))
mark this as a translation string.

2021-09-02 13:26 UTC, tasawernawaz requested changes
Thanks, @tehreem-sadat for working so hard on this in such a short time period and bringing this up.
Overall it is a great work, just a few suggestions, and comments.

2021-09-02 13:26 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/api/v0/serializers.py
> +class ConversationSerializer(serializers.ModelSerializer):
this serializer has common fields and methods as `ConversationAccessSerializer`, can we use inheritance here?

2021-09-02 13:26 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/api/v0/views.py
> +    serializer_class = ConversationSerializer
we should use the current user as the sender, otherwise, any logged-in user can create a message on the behalf of any other two users

2021-09-02 13:26 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/api/v0/views.py
> +    authentication_classes = (SessionAuthentication,)
we aren't consistent with this authentication class, this isn't being used in Bulk creation.

2021-09-02 13:26 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/signals.py
> +            )
just a suggestion you can clean this if by checking if not created at the top

2021-09-02 13:26 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/static/messenger/js/client/index.js
> +}
nit: new line

2021-09-02 13:26 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/static/messenger/js/components/Conversation/index.js
> +                                    <h2>{message.message}</h2>
make sure once we get the actual design we will apply css through classes.

2021-09-03 13:35 UTC, tehreem-sadat commented on openedx/features/wikimedia_features/messenger/models.py
> +            models.Index(fields=['sender', 'receiver']),
Django create individual index but here we need composite index as mostly we will use query containing both sender and receiver.

2021-09-03 13:37 UTC, tehreem-sadat commented on openedx/features/wikimedia_features/messenger/api/v0/serializers.py
> +        if request:
as this is custom method, so we want to make sure that no one should be allowed to call this method without request object.

2021-09-03 13:39 UTC, tehreem-sadat commented
@tasawernawaz I have done all suggested changes except 2 for which I have mentioned the reasons on your comments. Please review it again.

2021-09-07 05:30 UTC, tasawernawaz approved these changes
Just one minor comment, otherwise LGTM

2021-09-07 05:30 UTC, tasawernawaz commented on openedx/features/wikimedia_features/messenger/api/v0/views.py
> +            "username": "username1"
this docstring needs to be updated now

2021-09-07 07:47 UTC, merged